ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.PrintName = "Terminal"
ENT.Author = "Zephri"
ENT.Contact	= ""
ENT.Purpose	= "Allows players to create and spawn vehicles."
ENT.Instructions = "Spawn it in where you want, setup the spawn-area and save."
ENT.Category = "Dynamic Vehicles"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.AdminOnly = true
